CREATE TABLE ST62226.Fish(
    ID INTEGER NOT NULL,
    name CHAR(20),
    YearOfbirth DECIMAL(4),
    color1 CHAR(10),
    color2 CHAR(10),
    color3 CHAR(10),
    color4 CHAR(10),
    Number INTEGER NOT NULL
);

CREATE TABLE ST62226.Species(
    Number INTEGER NOT NULL,
    Title CHAR(20),
    Habitat CHAR(20),
    type CHAR(15)
);
CREATE TABLE ST62226.Food
(
    title CHAR(10) NOT NULL,
    quantity DECIMAL(8,2),
    unit CHAR(10)
);

CREATE TABLE ST62226.Eat(
    fish_id INTEGER NOT NULL,
    food_title CHAR(10) NOT NULL,
    feedDatetime TIMESTAMP NOT NULL,
    quantity DECIMAL(6,2),
    unit CHAR(10)
);

CREATE TABLE ST62226.Tank(
    ID INTEGER NOT NULL,
    length SMALLINT,
    width SMALLINT,
    depth SMALLINT,
    waterlevel CHAR(5),
    lastCleaningDate DATE
);

CREATE TABLE ST62226.Swim(
    TankID INTEGER NOT NULL,
    FishID INTEGER NOT NULL,
    startSwimDate DATE
);

ALTER TABLE ST62226.Fish ADD CONSTRAINT "Fish_PK" PRIMARY KEY (ID);

ALTER TABLE ST62226.Species ADD CONSTRAINT "Species_PK" PRIMARY KEY (Number);

ALTER TABLE ST62226.Fish ADD CONSTRAINT "Fish_Species_FK" FOREIGN KEY (Number)
REFERENCES ST62226.Species(Number) ON DELETE CASCADE;


ALTER TABLE ST62226.Food ADD CONSTRAINT "Food_PK" PRIMARY KEY (title);

ALTER TABLE ST62226.Eat ADD CONSTRAINT "Eat_PK" PRIMARY KEY (feedDatetime,fish_id,food_title);

ALTER TABLE ST62226.Eat ADD CONSTRAINT "Fish_ID_FK" FOREIGN KEY (fish_id)
REFERENCES ST62226.Fish(ID) ON DELETE CASCADE;

ALTER TABLE ST62226.Eat ADD CONSTRAINT "Food_Title_FK" FOREIGN KEY (food_title)
REFERENCES ST62226.Food(title) ON DELETE CASCADE;

ALTER TABLE ST62226.Tank ADD CONSTRAINT "Tank_PK" PRIMARY KEY (ID);

ALTER TABLE ST62226.Swim ADD CONSTRAINT "Swim_PK" PRIMARY KEY (TankID,FishID);

ALTER TABLE ST62226.Swim ADD CONSTRAINT "TankID_FK" FOREIGN KEY (TankID)
REFERENCES ST62226.Tank(ID) ON DELETE  CASCADE ;

ALTER TABLE ST62226.Swim ADD CONSTRAINT "FishID_FK" FOREIGN KEY (FishID)
REFERENCES ST62226.Fish(ID) ON DELETE  CASCADE ;
