create table STATION
(
    CITY     VARCHAR(255),
    DISTRICT VARCHAR(255),
    CHIEF_NO VARCHAR(255)
);

INSERT INTO PUBLIC.STATION (CITY, DISTRICT, CHIEF_NO) VALUES ('Bangkok', 'Phayathai', null);
INSERT INTO PUBLIC.STATION (CITY, DISTRICT, CHIEF_NO) VALUES ('Bangkok', 'Ram', null);
INSERT INTO PUBLIC.STATION (CITY, DISTRICT, CHIEF_NO) VALUES ('Bangkok', 'Chomthong', null);
INSERT INTO PUBLIC.STATION (CITY, DISTRICT, CHIEF_NO) VALUES ('Japan', 'Osaka', null);