-- 1) SELECT * FROM department;
SELECT * FROM ST62226.DEPARTMENT;
-- 2) SELECT * FROM employee;
SELECT * FROM ST62226.EMPLOYEE;
-- 3) SELECT * FROM project;
SELECT * FROM ST62226.PROJECT;
-- 4) SELECT * FROM empprojact;
SELECT * FROM ST62226.EMPPROJACT;
-- 5) FIND FEMALE EMPLOYEES, SHow their name,date of birth,phone and salary
SELECT FIRSTNME,LASTNAME,BIRTHDATE,PHONENO,SALARY
FROM ST62226.EMPLOYEE
WHERE SEX = 'F';
-- 6) Find name,job, and salary of employee who earns more than $80000
SELECT FIRSTNME,LASTNAME,JOB,SALARY
FROM ST62226.EMPLOYEE
WHERE SALARY > 80000
-- 6.2) IS THERE WOMAN IN THERE ?
SELECT FIRSTNME,LASTNAME,JOB,SALARY
FROM ST62226.EMPLOYEE
WHERE SALARY > 80000 and SEX = 'F';
-- 6.3) ORDER THE RESULT OF 6.2 by salaray. show the highest salary first.
SELECT FIRSTNME,LASTNAME,JOB,SALARY
FROM ST62226.EMPLOYEE
WHERE SALARY > 80000 and SEX = 'F'
ORDER BY SALARY DESC
-- 7) Show name,job,salary,and hiredate of the top three most salary employees.
SELECT FIRSTNME,LASTNAME,JOB,SALARY,BIRTHDATE
FROM ST62226.EMPLOYEE
ORDER BY SALARY DESC
FETCH FIRST 3 rows only
-- or
SELECT FIRSTNME,LASTNAME,JOB,SALARY,BIRTHDATE
FROM ST62226.EMPLOYEE
ORDER BY SALARY DESC
LIMIT 3
-- 8) Show name and their total income
SELECT FIRSTNME, LASTNAME, SALARY, BONUS, COMM, SALARY + BONUS + COMM AS TOTAL
FROM ST62226.EMPLOYEE;
-- 9) Show only persons who earn the total income more than $100,000 Order the result by lastname
SELECT FIRSTNME, LASTNAME, SALARY + BONUS + COMM AS TOTAL
FROM ST62226.EMPLOYEE
WHERE (SALARY + BONUS + COMM ) > 100000
ORDER BY LASTNAME;
-- 10) Who would earn more than 75000 if the company raise salary by 5%?
SELECT FIRSTNME, LASTNAME, SALARY,SALARY*1.05 AS NEW_SALARY
FROM ST62226.EMPLOYEE
WHERE (SALARY*1.05) > 75000
ORDER BY LASTNAME;
-- 11) Who cross the 75000 if the company raise the salary by 5% ?
SELECT FIRSTNME, LASTNAME, SALARY,SALARY*1.05 AS NEW_SALARY
FROM ST62226.EMPLOYEE
WHERE (SALARY*1.05) > 75000 and SALARY < 75000
ORDER BY LASTNAME;
-- 12) Who are older than 45 years?
SELECT FIRSTNME,LASTNAME, year(CURRENT_DATE - BIRTHDATE) AS AGE
FROM ST62226.EMPLOYEE
WHERE year(CURRENT_DATE - BIRTHDATE) > 45;
-- 13) Show name,job title, and their department
SELECT FIRSTNME, LASTNAME, JOB, DEPTNAME
FROM ST62226.EMPLOYEE, ST62226.DEPARTMENT
WHERE WORKDEPT = DEPTNO;

-- 14) Who are the missing person of question 14 ?
SELECT FIRSTNME, LASTNAME, JOB
FROM ST62226.EMPLOYEE
WHERE WORKDEPT  NOT IN (SELECT DEPTNO FROM DEPARTMENT);
-- before midterm
SELECT FIRSTNME,WORKDEPT
FROM ST62226.EMPLOYEE
WHERE WORKDEPT = 'A01';
-- 15) Show all detail of project
SELECT *
FROM ST62226.PROJECT;
-- 16) Opol wants to know who works on payroll project
SELECT  FIRSTNME,LASTNAME,EMPLOYEE.EMPNO,PROJNAME
FROM ST62226.EMPPROJACT,ST62226.PROJECT,ST62226.EMPLOYEE
WHERE EMPPROJACT.PROJNO = PROJECT.PROJNO
    AND PROJNAME LIKE 'PAYROLL PROGRAMMING'
    AND EMPLOYEE.EMPNO =EMPPROJACT.EMPNO;
-- 17) Opol complains "DO NOT SHOW ME THE REPEATING RESULT!"
SELECT DISTINCT FIRSTNME,LASTNAME,EMPLOYEE.EMPNO,PROJNAME
FROM ST62226.EMPPROJACT,ST62226.PROJECT,ST62226.EMPLOYEE
WHERE EMPPROJACT.PROJNO = PROJECT.PROJNO
    AND PROJNAME LIKE 'PAYROLL PROGRAMMING'
    AND EMPLOYEE.EMPNO =EMPPROJACT.EMPNO;
-- 18) Opol said i want any payroll project, not only payroll programming. I'm programmer. I knew your SQL.
-- your SQL selects only "PAYROLL PROGRAMMING" not any "PAYROLL"
SELECT DISTINCT FIRSTNME,LASTNAME,EMPLOYEE.EMPNO,PROJNAME
FROM ST62226.EMPPROJACT,ST62226.PROJECT,ST62226.EMPLOYEE
WHERE EMPPROJACT.PROJNO = PROJECT.PROJNO
    AND PROJNAME LIKE '%PAYROLL%'
    AND EMPLOYEE.EMPNO =EMPPROJACT.EMPNO;
-- 19) Who works on the project that start before 2010-01-01. Show their name and their department name.
SELECT DISTINCT FIRSTNME,LASTNAME,DEPTNAME
FROM ST62226.DEPARTMENT, ST62226.EMPLOYEE, ST62226.EMPPROJACT, ST62226.PROJECT
WHERE DEPARTMENT.DEPTNO = EMPLOYEE.WORKDEPT AND
      EMPLOYEE.EMPNO = EMPPROJACT.EMPNO AND
      EMPPROJACT.PROJNO = PROJECT.PROJNO AND
      PRSTDATE < '2010-01-01';
-- 20) Who are old than the president
SELECT e.FIRSTNME, e.lastname, e.BIRTHDATE,p.BIRTHDATE
FROM EMPLOYEE as p, EMPLOYEE as e
WHERE p.JOB LIKE 'PRES%' and e.BIRTHDATE < p.BIRTHDATE;
-- OR
SELECT FIRSTNME,LASTNAME, year(CURRENT_DATE - BIRTHDATE) AS AGE
FROM ST62226.EMPLOYEE
WHERE BIRTHDATE < (SELECT BIRTHDATE FROM ST62226.EMPLOYEE WHERE JOB LIKE 'PRES%');
