-- ISONLATION LEVEL
-- PROBLEM              ANSI SQL            DB2
-- Phantom Read     2 SERIALIZABLE          Repeatable Read (RR)
-- Incorrect Sum    3 REPEATABLE READ       Read stability (RS)
-- Dirty Read       2 READ COMMITTED        Cursor Stability (CS)
-- Lost Update      1 READ UNCOMMITTED      Uncommitted Read (UR)
--

-- SELECT * FROM EMPLOYEE;
-- Example 0

UPDATE EMPLOYEE SET SALARY = 20000 WHERE EMPNO = '000020';

SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';
commit;
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';

-- Example 0.2

UPDATE EMPLOYEE SET SALARY = 30000 WHERE EMPNO = '000020';
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';
ROLLBACK;
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';

-- Example 0.3

UPDATE EMPLOYEE SET SALARY = 40000 WHERE EMPNO = '000020';
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';
commit;
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';
rollback;
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';

-- Example 1

UPDATE EMPLOYEE SET SALARY = 20000 WHERE EMPNO = '000020';
commit;

SET CURRENT ISOLATION LEVEL UR
commit;


UPDATE EMPLOYEE SET SALARY = 30000 WHERE EMPNO = '000020';
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';

commit;

UPDATE EMPLOYEE SET SALARY = 70000 WHERE EMPNO = '000020';
SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';

SELECT FIRSTNME,LASTNAME,SALARY FROM EMPLOYEE WHERE EMPNO ='000020';
